### ISSUE TITLE
JCenter support

### ISSUE THREAD

**Issue by ReginFell** [processout/processout-android#22]
At the moment the library requires `volley` that is available only in `jCenter` which will be closed 1 of May

**Comment by adamszewe** [comment]
At the moment Volley team is working on releasing the version 1.2.0 either on maven central or on maven google:
https://github.com/google/volley/issues/394

**Comment by ReginFell** [comment]
Hey @adamszewe, Google released Volley 1.2.0 recently, do you have any plans to update `processout-sdk`?

**Comment by PhilippeBoisney** [comment]
Do you have any updates on this migration? We don't support `jcenter()` in our app and we had to manually authorize it in our codebase because of the outdated `Volley` dependency...

This issue was created **1 year ago**, and many libraries used by this SDK are still outdated... Is this SDK still maintained? 👇 

<img width="848" alt="image" src="https://user-images.githubusercontent.com/6847959/205627122-f89897f6-9ce0-438e-bc39-8babeace4e18.png">

**Comment by simeon-kostadinov-cko** [comment]
We upgraded the libraries the sdk uses in the latest release. https://github.com/processout/processout-android/releases/tag/2.18.4
